### ISSUE TITLE
Doesn't seem to be working with sketch 3.4 update

### ISSUE THREAD

**Issue by zacdicko** [timuric/Content-generator-sketch-plugin#76]
Doesn't seem to be working with sketch 3.4 update

**Comment by shiienurm** [comment]
Confirming the same issue.

**Comment by marcusandrew** [comment]
Yup. Not working here either.

**Comment by timuric** [comment]
@zacdicko @shiienurm @marcusandrew It does work for me. Can you please share version of your Sketch app `Sketch\About Sketch` 
Also, do you have a release from the Appstore or downloaded from the website?

**Comment by Elyager** [comment]
I have Version 3.4 (15588)  and is not working, I just updated from the app update notification.

**Comment by Elyager** [comment]
I just reinstalled the plugin and now is working :+1:

**Comment by timuric** [comment]
Can you please send a log from the console app. Simply type sketch in the console.app, then run the plugin

**Comment by hassaan22** [comment]
Also experiencing issues.

**Comment by HectorCalleja** [comment]
Same here :(

Reinstalled and still not working. Killing my workflow

Best

**Comment by timuric** [comment]
Please submit log details, otherwise I don't know what is going wrong

**Comment by HectorCalleja** [comment]
How can I do this? It doesn´t return any error message, just don´t work

Best & Thanks! :D

**Comment by timuric** [comment]
@HectorCalleja You can do it by following these steps:
1. Open Console app `Applications/Utilities/Console` 
2. Type `Sketch` In filter box
3. Run plugin
4. Copy the contents in the Console app

**Comment by HectorCalleja** [comment]
Thank you so much!

This is what happens when I execute the plugin on a circle to add a photo

29/10/15 15:56:27,863 Sketch[176]: Deprecation Warning in :
/Users/Hec/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Content-generator-sketch-plugin-master/Photos/Music
artist.sketchplugin, line 0 «Plugin Developer»
29/10/15 15:56:27,863 Sketch[176]: Warning: #import syntax for CocoaScript
is deprecated. Please update your script to use @import instead. «Plugin
Developer»
29/10/15 15:56:27,865 Sketch[176]: Deprecation Warning in :
/Users/Hec/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application
Support/com.bohemiancoding.sketch3/Plugins/Content-generator-sketch-plugin-master/Photos/Music
artist.sketchplugin, line 1 «Plugin Developer»
29/10/15 15:56:27,865 Sketch[176]: Warning: #import syntax for CocoaScript
is deprecated. Please update your script to use @import instead. «Plugin
Developer»


Best!

**Comment by timuric** [comment]
@HectorCalleja I think it is fixed now, please get a new version. Let me know if it works for you

**Comment by HectorCalleja** [comment]
It worked!!!

Thank you so mucho brother

Shot outs from Madrid :D

**Comment by timuric** [comment]
@HectorCalleja Thanks for feedback!

@hassaan22 @Elyager @marcusandrew @zacdicko Please update

**Comment by marcusandrew** [comment]
Nice work Timuric. You've been awesome.

Sketch is not complete without your plugin :)

**Comment by timuric** [comment]
@marcusandrew haha, thanks!

**Comment by HectorCalleja** [comment]
Co-sign

:)

**Comment by zacdicko** [comment]
All Good man, nice work!
